version: '3.9'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    working_dir: /frontend-docker
    volumes:
      - ./frontend:/frontend-docker
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    tty: true
    stdin_open: true
    ports:
      - 3001:3001
      - 4000:4000
    working_dir: /backend-docker
    volumes:
      - ./backend:/backend-docker
    depends_on:
      - db-mysql
  db-mysql:
    container_name: db-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=899899
    ports:
      - 33066:3306