version: '3.9'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    working_dir: /frontend-docker
    volumes:
      - ./frontend:/frontend-docker
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    tty: true
    stdin_open: true
    environment:
      - DB_USER=root
      - DB_PASS=899899
      - DB_HOST=db-mysql
      - DB_PORT=3306
    ports:
      - 3001:3001
      - 4000:4000
    working_dir: /backend-docker
    volumes:
      - ./backend:/backend-docker
    depends_on:
      - db-mysql
      - db-mongodb
  db-mysql:
    container_name: db-mysql
    image: mysql:latest
    restart: 'always'
    environment:
      - MYSQL_ROOT_PASSWORD=899899
    ports:
      - 33066:3306
  db-mongodb:
    container_name: db-mongodb
    image: mongo:latest
    restart: 'always'
    ports:
      - 27018:27017
